### ISSUE TITLE
Very encouraging

### ISSUE THREAD

**Issue by scherepanov** [dingqiangliu/vertica_export#1]
I thought about writing something like this for a long time, primary to improve speed of Vertica client
Finally I get pointed to this repo
Took me three days to write my version. Unfortunately I cannot posted to open source.
What I did differently:
- Allow to compress into zstd(default) or lz4, or uncompressed data. Network transfer in compressed form, file written in compressed form. Provide big boost.
- I am using ncat as receiver on client node, started through ssh, it opens connection back to Vertica node, based on parameters in command line
- no encryption
- printing output with stats - file names, sizes comp/uncomp, times, speeds
- no support to other destinations than cat over ssh
- timestamps and dates types are forced into int, number of micros since unix epoch, number of years since unix epoch. Conversion back/forth between time and string is the most resource consuming part of csv convertor. And, on client it is easier to digest int than formatted time/date string.
Performance is quite good, it is around 15 times faster than standard vsql to csv file.
When using partition nodes (one node per file), performance is over 3 orders of magnitude faster than vsql. Of course, ordering being lost in this case.
I was not able to get performance numbers for partition best - on my production 45-node cluster 16 instances of UDx being spawn in parallel, that leads to over 600 simultaneous ssh connections to client. Even if ssh configured to accept it, then it runs into resource limits on opening connections etc. This does not scale properly and needs special client. 
So... thanks for encouraging.

**Comment by dingqiangliu** [comment]
Good to know your idea.
Vertica has a new statement, Export to Parquet, to boost performance much more. This project is maintained for compatibility with works before, or somewhere CSV output required.
